//{{NO_DEPENDENCIES}}
// Include file generated by Microsoft Visual C++.
// Used by GLPI-AgentMonitor.rc
//
#define IDFORCE                         1
#define IDI_GLPIOK                      5
#define IDR_MAINFRAME                   100
#define IDR_RMENU                       141
#define IDI_GLPIERR                     148
#define IDB_LOGO                        152
#define IDS_STRING153                   153
#define STRING                          153
#define IDS_APP_TITLE                   200
#define IDS_GLPINOTIFYERROR             201
#define IDS_GLPINOTIFY                  202
#define IDS_INFO                        203
#define IDS_STATIC_INFO                 203
#define IDS_AGENTVER                    204
#define IDS_STATIC_AGENTVER             204
#define IDS_SERVICESTATUS               205
#define IDS_STATIC_SERVICESTATUS        205
#define IDS_STARTTYPE                   206
#define IDS_STATIC_STARTTYPE            206
#define IDS_LOADING                     208
#define IDS_AGENTSTATUS                 209
#define IDS_STATIC_AGENTSTATUS          209
#define IDS_FORCEINV                    210
#define IDS_CLOSE                       211
#define IDS_ERR_NOTRESPONDING           212
#define IDS_AGENTSTATUSINFO             213
#define IDS_ERR_NOTRUNNING              213
#define IDS_SVCSTART_BOOT               214
#define IDS_SVCSTART_SYSTEM             215
#define IDS_SVCSTART_AUTO               216
#define IDS_SVCSTART_DELAYEDAUTO        217
#define IDS_SVCSTART_MANUAL             218
#define IDS_SVCSTART_DISABLED           219
#define IDS_ERR_UNKSVCSTART             220
#define IDS_ERR_REGFAIL                 221
#define IDS_ERR_AGENTVERNOTFOUND        222
#define IDS_ERR_AGENTNOTFOUND           223
#define IDS_SVC_STOPPED                 225
#define IDS_SVC_RUNNING                 226
#define IDS_SVC_PAUSED                  227
#define IDS_SVC_CONTINUEPENDING         228
#define IDS_SVC_PAUSEPENDING            229
#define IDS_SVC_STARTPENDING            230
#define IDS_SVC_STOPPENDING             231
#define IDS_ERR_SERVICE                 232
#define IDS_OK                          233
#define IDS_ERROR                       234
#define IDS_ERR_FORCEINVNO_RESPONSE     235
#define IDS_ERR_FORCEINV_NORESPONSE     235
#define IDS_ERR_FORCEINV_NOTALLOWED     236
#define IDS_MSG_FORCEINV_OK             237
#define IDS_ERR_AGENTERR                238
#define IDS_RMENU_OPEN                  239
#define IDS_RMENU_FORCE                 240
#define IDS_RMENU_EXIT                  241
#define IDS_FILE                        242
#define IDS_DIR                         243
#define IDD_GLPIAGENTMONITORCPP_DIALOG  400
#define IDD_DIALOG1                     401
#define IDD_MAIN                        402
#define IDC_GLPIAGENTMONITORCPP         600
#define IDC_LBFIVER                     601
#define IDC_LBFMVER                     601
#define IDC_VERSION                     601
#define IDC_GBMAIN                      602
#define IDC_GBSTATUS                    603
#define IDC_LBSTATUS                    604
#define IDC_AGENTSTATUS                 604
#define IDC_LBVER                       605
#define IDC_AGENTVER                    605
#define IDC_LBSVCSTATUS                 606
#define IDC_SERVICESTATUS               606
#define IDC_LBSTARTUP                   607
#define IDC_STARTTYPE                   607
#define IDC_PCLOGO                      609
#define IDT_UPDSTATUS                   610
#define IDC_STATIC_AGENTVER             1004
#define IDC_STATIC_SERVICESTATUS        1005
#define IDC_STATIC_STARTTYPE            1006
#define ID_RMENU_OPEN                   32760
#define ID_RMENU_FORCE                  32761
#define ID_RMENU_EXIT                   32762
#define IDC_STATIC                      -1
#define IDC_STATIC_TITLE                -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
