#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
  configure)
    [ -d "/etc/glpi-agent" ] || mkdir "/etc/glpi-agent"
    [ -d "/etc/glpi-agent/conf.d" ] || mkdir "/etc/glpi-agent/conf.d"
    for conf in agent inventory-server-plugin ssl-server-plugin server-test-plugin \
        proxy-server-plugin proxy2-server-plugin toolbox-plugin
    do
        ucf /usr/share/glpi-agent/etc/$conf.cfg /etc/glpi-agent/$conf.cfg
        ucfr glpi-agent /etc/glpi-agent/$conf.cfg
    done
    ;;
esac

exit 0
