#!/usr/bin/perl

use strict;
use warnings;
use Digest::SHA;
use UNIVERSAL::require;
use File::Find;
use Getopt::Long;
use File::Spec;

my ($dir, $key_file, $help);

GetOptions(
    'dir=s' => \$dir,      # Directory of the package to sign
    'key=s' => \$key_file, # File containing the private key
    'help'  => \$help,
);

if ($help || !$dir || !$key_file) {
    print "Usage: $0 --dir <directory> --key <private_key_file>\n";
    print "\nOptions:\n";
    print "  --dir <directory>  Directory containing the files to be deployed\n";
    print "  --key <file>       File containing your Ed25519 private key (hex or PEM format)\n";
    exit;
}

# 1. Load private key
unless (Crypt::Ed25519->require()) {
    die "Error: Crypt::Ed25519 perl module is required on this system to sign packages.\n";
}

my $content;
if (open my $kh, '<', $key_file) {
    $content = do { local $/; <$kh> };
    close $kh;
} else {
    die "Can't open key file '$key_file': $!";
}

my $seed;
if ($content =~ /-----BEGIN/) {
    # PEM format
    require MIME::Base64;
    $content =~ s/-----BEGIN.*?-----//sg;
    $content =~ s/-----END.*?-----//sg;
    $seed = MIME::Base64::decode_base64($content);

    # Handle PKCS#8 Ed25519 (48 bytes)
    if (length($seed) == 48) {
        # Extract 32-byte seed from PKCS#8
        $seed = substr($seed, -32);
    }
} else {
    # Hex format
    $content =~ s/\s+//g;
    $seed = pack("H*", $content);
}

if (length($seed) != 32) {
    die "Error: Private key seed must be 32 bytes (got " . length($seed) . " bytes). Check your key format.\n";
}

# 2. Generate manifest (SHA-512 of each file)
my $manifest = "";
my @files;
my $abs_dir = File::Spec->rel2abs($dir);

File::Find::find(sub {
    return if -d $_;
    return if $_ eq 'signature.sig' || $_ eq 'manifest.sig';

    # Calculate relative path from the root of $dir
    # We use $abs_dir calculated outside find() because find() chdirs into directories
    my $rel_path = File::Spec->abs2rel(File::Spec->rel2abs($_), $abs_dir);
    push @files, $rel_path;
}, $dir);

foreach my $file (sort @files) {
    my $path = File::Spec->catfile($dir, $file);
    my $sha = Digest::SHA->new(512);
    $sha->addfile($path, 'b');
    $manifest .= $sha->hexdigest . " $file\n";
}

# 3. Sign the manifest
# GAAS version of Crypt::Ed25519:
# generate_keypair($seed) returns ($public_32, $private_64)
# sign($message, $public_32, $private_64) returns $signature_64
my ($pub_bin, $priv_bin) = Crypt::Ed25519::generate_keypair($seed);
my $signature_bin = Crypt::Ed25519::sign($manifest, $pub_bin, $priv_bin);
my $signature_hex = unpack("H*", $signature_bin);

# 4. Write signature.sig
my $sig_file = File::Spec->catfile($dir, 'signature.sig');
open my $sh, '>', $sig_file or die "Can't write signature file '$sig_file': $!";
print $sh $signature_hex, "\n", $manifest;
close $sh;

print "Success: Package signed successfully in $sig_file\n";

__END__

=head1 NAME

glpi-sign-package.pl - Sign a deployment package for GLPI Agent

=head1 SYNOPSIS

glpi-sign-package.pl --dir <directory> --key <private_key_file>

Options:
  --dir <directory>  Directory containing the files to be signed
  --key <file>       File containing your Ed25519 private key
  --help             Display this help message

=head1 DESCRIPTION

This tool creates a signed manifest (C<signature.sig>) for a directory intended 
to be used with the GLPI Agent C<Deploy> task.

It performs the following steps:
1. Scans the target directory for all files (excluding existing signatures).
2. Calculates a SHA-512 hash for each file.
3. Generates a manifest containing these hashes and their relative paths.
4. Signs the manifest using the provided Ed25519 private key.
5. Writes the signature and the manifest into a C<signature.sig> file at the 
   root of the target directory.

=head1 KEY FORMATS

The tool supports Ed25519 private keys in the following formats:

=over 4

=item * B<PEM (PKCS#8)>: Standard format generated by OpenSSL or ssh-keygen.

  -----BEGIN PRIVATE KEY-----
  MC4CAQAwBQYDK2VwBCIEIMUWFFWvbK9uT2P1mNVviQzshQhRMm7440fImmCYW8Jj
  -----END PRIVATE KEY-----

=item * B<Raw Hex>: A 64-character hexadecimal string representing the 32-byte 
secret seed.

  c5161455af6caf6e4f63f598d56f890cec850851326ef8e347c89a60985bc263

=back

=head1 EXAMPLES

=head2 Sign a directory using a PEM key

  perl tools/glpi-sign-package.pl --dir /path/to/payload --key my_private.key

=head2 Sign a directory using a hex key

  echo "c5161455af6caf6e4f63f598d56f890cec850851326ef8e347c89a60985bc263" > hex.key
  perl tools/glpi-sign-package.pl --dir /path/to/payload --key hex.key

=head1 REQUIREMENTS

This tool requires the C<Crypt::Ed25519> Perl module.

=head1 SEE ALSO

L<GLPI::Agent::Task::Deploy>
