name: GLPI Agent MacOSX Packaging

on:
  push:
    branches:
    - feature/github-action-macosx-packaging
    - develop
    tags-ignore:
    - '**'

jobs:
  macosx-packaging:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build package
      run: |
        ./contrib/macosx/glpi-agent-packaging.sh
      shell: bash
    - name: List generated files
      if: success() || failure()
      run: |
        ls contrib/macosx/build
      shell: bash
    - name: Upload PKG-Build artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v1
      with:
        name: MacOSX-PKG-Build
        path: contrib/macosx/build
